name: Sync Leetcode

on:
  workflow_dispatch: # Allows you to manually trigger the sync anytime
  schedule:
    - cron: "0 8 * * 6" # Automatically runs every Saturday at 8:00 AM UTC

permissions:
  contents: write # Forces GitHub to give this script write access to your repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: . # Keeps files at the root level. Change if you want a sub-folder (e.g., 'solutions')
          verbose: true
          commit-header: "[LeetCode Sync]"
